language: cpp

os:
 - linux
 - osx

dist:
 - xenial

addons:
  homebrew:
    packages:
      - qt5
    update: true
  apt:    
    sourceline: ppa:beineri/opt-qt-5.11.0-xenial
    packages:
      - qt5-default
      - libqt5opengl5-dev
      - python3-dev
      - pkg-config
    update: true

before_install:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew link qt5 --force; fi

script:
  - mkdir build && cd build
  - qmake ..
  - make -j4
